/** @type {import('prettier').Config} */
const config = {
  singleQuote: true,
  semi: false,
  trailingComma: 'es5',
  tabWidth: 2,
  printWidth: 120,
  endOfLine: 'lf',
  arrowParens: 'avoid',
  htmlWhitespaceSensitivity: 'css',
  vueIndentScriptAndStyle: false,
  singleAttributePerLine: false,
  useTabs: false,
  quoteProps: 'as-needed',
  jsxSingleQuote: false,
  bracketSpacing: true,
  bracketSameLine: false,
  attributeGroups: [
    '^(v-is|is|:is)$',
    '^v-for$',
    '^v-(if|else-if|else|show|cloak)$',
    '^(v-once|v-pre)$',
    '^:?(id)$',
    '^:?(key|ref)$',
    '^(v-slot|slot)$',
    '^v-model$',
    '^v-',
    '^role$',
    '^(:|v-bind)',
    '$DEFAULT',
    '^(@|v-on(?::|$))',
    '^v-(html|text)$',
    '^#',
  ],
  attributeSort: 'ASC',
  plugins: ['prettier-plugin-organize-attributes'],
}

export default config
