export default {
  singleQuote: true,
  semi: false,
  trailingComma: 'es5',
  tabWidth: 2,
  printWidth: 120,
  endOfLine: 'lf',
  arrowParens: 'avoid',
  htmlWhitespaceSensitivity: 'ignore',
  vueIndentScriptAndStyle: false,
  singleAttributePerLine: false,
  useTabs: false,
  quoteProps: 'as-needed',
  jsxSingleQuote: false,
  bracketSpacing: true,
  bracketSameLine: false,
  attributeGroups: [
    '^(v-is|is)$',
    '^v-for$',
    '^v-(if|else-if|else|show|cloak)$',
    '^(v-once|v-pre)$',
    '^:?(id|key|ref)$',
    '^(v-slot|slot)$',
    '^v-model',
    '^(@|v-on(?::|$))',
    '^v-(html|text|bind)$',
    '^#',
    '$DEFAULT',
    '^aria-',
  ],
  attributeSort: 'ASC',
  plugins: ['prettier-plugin-organize-attributes'],
}
